/* AUTO-GENERATED by pack_assets.py — do not edit */
#ifndef ASSETS_GEN_H
#define ASSETS_GEN_H
#include <stdint.h>

typedef struct {
  const char *name;
  uint16_t w, h;
  const uint8_t *pix;
} terse_asset_t;

extern const uint8_t pat_GORF_PAT[156];
extern const terse_asset_t asset_GORF_PAT;
extern const uint8_t pat_PLY1_P[240];
extern const terse_asset_t asset_PLY1_P;
extern const uint8_t pat_PLY2_P[240];
extern const terse_asset_t asset_PLY2_P;
extern const uint8_t pat_LAZON[208];
extern const terse_asset_t asset_LAZON;
extern const uint8_t pat_SBASE[64];
extern const terse_asset_t asset_SBASE;

#define TERSE_ASSET_COUNT 5
extern const terse_asset_t *const terse_assets[TERSE_ASSET_COUNT];

#endif
