#!/usr/bin/env python3
"""Pack authentic patterns from play/assets.json into C arrays for the SDL runtime.

Primary source is assets.json (same export as the pattern lab). Optionally
cross-checks GORF-PAT against tools.terse.parse on MSGORPAT GORF-P.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
ASSETS = ROOT / "play" / "assets.json"
GORF_P = ROOT / "extracted" / "msgorf_floppy_files" / "MSGORPAT_Disk" / "GORF-P"
OUT_H = Path(__file__).resolve().parent / "assets_gen.h"
OUT_C = Path(__file__).resolve().parent / "assets_gen.c"

# Patterns required for harness demo (names as stored in assets.json)
NEED = ["GORF-PAT", "PLY1-P", "PLY2-P", "LAZON", "SBASE"]


def main() -> None:
    data = json.loads(ASSETS.read_text())
    patterns = data["patterns"]
    missing = [n for n in NEED if n not in patterns]
    if missing:
        raise SystemExit(f"missing patterns in assets.json: {missing}")

    if GORF_P.exists():
        from tools.terse.parse import parse_file

        parsed = parse_file(GORF_P)
        g = next((p for p in parsed["patterns"] if p["name"] == "GORF-PAT"), None)
        if g and g["rows"] != patterns["GORF-PAT"]["rows"]:
            raise SystemExit("GORF-PAT mismatch: parse(GORF-P) vs assets.json")

    h_lines = [
        "/* AUTO-GENERATED by pack_assets.py — do not edit */",
        "#ifndef ASSETS_GEN_H",
        "#define ASSETS_GEN_H",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "  const char *name;",
        "  uint16_t w, h;",
        "  const uint8_t *pix;",
        "} terse_asset_t;",
        "",
    ]
    c_lines = [
        "/* AUTO-GENERATED by pack_assets.py — do not edit */",
        '#include "assets_gen.h"',
        "",
    ]

    externs = []
    for name in NEED:
        p = patterns[name]
        w, h = p["w"], p["h"]
        rows = p["rows"]
        pix = []
        for row in rows:
            for ch in row.ljust(w, "0")[:w]:
                pix.append(int(ch))
        ident = name.replace("-", "_")
        arr = f"pat_{ident}"
        h_lines.append(f"extern const uint8_t {arr}[{w * h}];")
        h_lines.append(f"extern const terse_asset_t asset_{ident};")
        externs.append(ident)
        c_lines.append(f"const uint8_t {arr}[{w * h}] = {{")
        for i in range(0, len(pix), 16):
            chunk = ", ".join(str(x) for x in pix[i : i + 16])
            c_lines.append(f"  {chunk},")
        c_lines.append("};")
        c_lines.append(
            f'const terse_asset_t asset_{ident} = {{ "{name}", {w}, {h}, {arr} }};'
        )
        c_lines.append("")

    h_lines.append("")
    h_lines.append(f"#define TERSE_ASSET_COUNT {len(externs)}")
    h_lines.append("extern const terse_asset_t *const terse_assets[TERSE_ASSET_COUNT];")
    h_lines.append("")
    h_lines.append("#endif")

    c_lines.append("const terse_asset_t *const terse_assets[TERSE_ASSET_COUNT] = {")
    for ident in externs:
        c_lines.append(f"  &asset_{ident},")
    c_lines.append("};")

    OUT_H.write_text("\n".join(h_lines) + "\n")
    OUT_C.write_text("\n".join(c_lines) + "\n")
    print(f"wrote {OUT_H.name} {OUT_C.name} ({len(externs)} patterns)")


if __name__ == "__main__":
    main()
